### ISSUE TITLE
Feature: ExtraHardMode integration

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#227]
I have recently installed [ExtraHardMode](https://www.spigotmc.org/resources/extra-hard-mode.19673/). It would be nice to have a multiplier to reflect the increased difficulty. For example:
```
 # WorldDifficulty
  world-difficulty-multiplier:
    difficulty:
      multiplier:
        peaceful: '0.5'
        easy: '0.75'
        normal: '1.0'
        hard: '1.0'
        extrahard: '1.5'
```
I suppose that would require integration, or at least recognition that EHM was configured in a particular world. An example of the relevant configuration node is
```
ExtraHardMode:
  Enabled Worlds:
  - world_yellowdog
```
