### ISSUE TITLE
[bug] Fishing is not giving any rewards.

### ISSUE THREAD

**Issue by FrozenBeard** [Rocologo/MobHunting#313]
I have set the rewards to drop 100% of the time when catching fish, but it never, ever triggers.

```
# ########################################################################
# Rewards for fishing
# ########################################################################
# Here is where you set the base prize in $ for catching a fish
fishing:

  # Set this to true if you want to disable all fishing rewards / features.
  disable-fishing-rewards: false
  rawfish: '0'
  rawfish-cmd: mobhunt head give {player} rawfish Raw_Fish 1 silent
  rawfish-cmd-desc: You got the head of a Raw Fish
  rawfish-cmd-run-chance: 1.0
  rawfish-head-prize: '0'
  rawsalmon: '0'
  rawsalmon-cmd: mobhunt head give {player} rawsalmon Raw_Salmon 1 silent
  rawsalmon-cmd-desc: You got the head of a Raw Salmon
  rawsalmon-cmd-run-chance: 1.0
  rawSalmon-head-prize: '0'
  clownfish: '0'
  clownfish-cmd: mobhunt head give {player} clownfish Clowfish 1 silent
  clownfish-cmd-desc: You got the head of a Clownfish
  clownfish-cmd-run-chance: 1.0
  clownfish-head-prize: '0'
  pufferfish: '0'
  pufferfish-cmd: mobhunt head give {player} pufferfish Pufferfish 1 silent
  pufferfish-cmd-desc: You got the head of a Pufferfish
  pufferfish-cmd-run-chance: 1.0
  pufferfish-head-prize: '0'
```
