### ISSUE TITLE
YAML issue config 5.4.7

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#359]
Spigot 1.12.2
MH 5.4.7-b577

One class of nodes is preceded by hyphen: _commands.chance_. Why the difference?

For example
```
mobs:
  blaze:
    enabled: true
    message: You got a Blaze skull and an Iron ingot.
    money:
      amount: '100.0'
      chance: 1.0
    commands:
    - chance: '0.0'
      cmd: give {player} iron_ingot 1
      message: ''
    - chance: '0.0'
      cmd: mobhunt head give {player} Blaze Blaze 1 silent
      message: ''
```
