### ISSUE TITLE
Reward not changing based on configs

### ISSUE THREAD

**Issue by DanielVip3** [Rocologo/MobHunting#520]
I was trying to change rewards amount for each mob. For example, I have this in my config.yml:
```yml
# ### Pig settings ###
  pig:
    enabled: true
    message: You killed a §1{killed}
    money:
      amount: '2'
      chance: 1.0
    commands:
    - chance: '0.05'
      cmd: give {player} Iron_ingot 1
    head:
      drophead: true
      value: '0'
      chance: 0.05
      message: §aThe §1{killed} §adropped a skull on the ground
```
with amount "2", but, when I kill a pig, I always get $10. I restarted server 3 times.
This is just an example, because this happens for every mob.
I don't know what is this caused by, I activated debug mode and seems that nothing went wrong.
I also have McMMO, MythicMobs and EliteMobs, and I configured the last two in their own config files in the MobHunting folder.
I also deactivated Bag of Golds, because I use TheNewEconomy and Vault as currency plugin.
What can I do?
