### ISSUE TITLE
Grinding disable money reward for spawner does not work

### ISSUE THREAD

**Issue by Darcion** [Rocologo/MobHunting#554]
where is our issue? we only want to get xp and items but not money.  But monsters drop also money.
```

grinding:
  enable_grinding_detection: false

  # Put the names of the worlds here where you want to disable grinding detection
  # You would typically do this in creative worlds.
  disable_grinding_detection_in_worlds:
  - worldname
  - worldname2

  # Killing stacked mobs (created by a mob stacking plugin) 
  # is by nature detected as grinding and by default allowed. If you want to the the grinding detection to detect
  # killings of stacked to be detected as gring, you must set grinding_stacked_mobs_allowed to false.
  grinding_stacked_mobs_allowed: true

  # Area grinding detection.
  # Enabling this prevents a player from earning too much money from using a mob grinder.
  # Set 'enable_grinding_detection: false' to disable the grinding detection.
  # OBS: You can whitelist an area to allow grinding using '/mobhunt whitelistarea <add|remove>'
  # if the area is detected as a grinding area. See also '/mobhunt checkgrinding'
  # For each kill MobHunting check the number of kills within the range
  # If number of kills exceeds 10, the reward will decrese with 10% until the 'number of deaths'
  # is reached, whereafter the reward will be zero.
  area:
    detect_grinding_areas: false
    grinding_detection_range: 15
    grinding_detection_number_of_death: 20
    disable_natural_item_drops_on_player_grinding: false
    disable_natural_xp_drops_on_player_grinding: false
    blacklist_player_grinding_spots_as_server_worldwide_spots: false

  # Detect Grinding Farms.
  # When this is true, the plugin will try to detect if the players has build a Mob Grinding Farm.
  # Farm detection can be completly disabled or you can whitelist an area using the whitelist
  # command if you want the players to harvest mobs from a farm.
  farms:
    detect_farms: true

    # Nether Gold Farm detection.
    # When this is true, the plugin will try to detect if the players has build a Nether Gold Farm.
    # There is no guarantie that the plugin can detect all types of Nether Gold farms, but it has
    # been testet on this one: https://www.youtube.com/watch?v=jQWG9Q7HoUA
    # When searching for grinding the plugin measures how many mobs dies per timeframe within a range.
    # Be careful if you chance this number there is a risk for false positives.
    nether_gold_farms:
      detect_nether_gold_farms: true
      seconds_to_search_for_grinding: 30
      range_to_search_for_grinding: 4.0
      number_of_deaths_when_searching_for_grinding: 5
      disable_natural_item_drops: false
      disable_natural_xp_drops: false

    # Enderman Farm detection.
    # When this is true, the plugin will try to detect if the players has build an enderman Farm.
    # There is no guarantie that the plugin can detect all types of Enderman Farms. When searching
    # for grinding the plugin measures how many mobs dies in the VOID per timeframe within a range.
    # Be careful if you chance this number there is a risk for false positives.
    endermanfarms:
      detect_enderman_farms: true
      seconds_to_search_for_grinding: 30
      range_to_search_for_grinding: 5.0
      number_of_deaths_when_searching_for_grinding: 5
      disable_natural_item_drops: false
      disable_natural_xp_drops: false

    # Other Farm detection.
    # When this is true, the plugin will try to detect if the players has build other Farms
    # where different mobs is falling into death. The plugin is still counting mobs which
    # dies from falling, with in a range and a time frame.
    otherfarms:
      detect_other_farms: true
      seconds_to_search_for_grinding: 30
      range_to_search_for_grinding: 4.0
      number_of_deaths_when_searching_for_grinding: 10
      disable_natural_item_drops: false
      disable_natural_xp_drops: false

  # ########################################################################
  # Mobspawner settings
  # ########################################################################
  spawners:

    # Can the players earn money on mobs spawned from mobspawners, eggs and from eggs from Dispensers?
    # If you disable this you are still able to get rewards from specific Spawners, if you white list the area 
    # using '/mh whitelistarea'.
    disable_money_rewards_from_mobspawners_and_eggs: true

    # Let the players get the naturally dropped items from mobs spawned from mobspawners, eggs and from eggs from Dispensers ?
    disable_naturally_dropped_items_from_mobspawners_and_eggs: false

    # Let the players get the naturally dropped XP from mobs spawned from mobspawners, eggs and from eggs from Dispensers ?
    disable_naturally_dropped_xp_from_mobspawners_and_eggs: false
```
