### ISSUE TITLE
Mobs are dropping too much money with Gringotts

### ISSUE THREAD

**Issue by skerit** [Rocologo/MobHunting#557]
I've set Gringott's decimal `digits` setting to 0 and MobHunting's `reward_rounding` to 1. 
(And my denominations are: 1 = gold ingot, 9 = gold nugget, 81 = gold block)

I then decreased the amount of money the mobs would drop, like this zombie setting:

```
  zombie:
    enabled: true
    message: You killed a §1{killed}
    money:
      amount: 1:3
      chance: 0.6
```

Then I killed a zombie, and I got this:

`Zombie dropped 5 Gold Nuggets, 3 Gold Ingots!`

I thought I'd get somewhere between 1 and 3 ingots, 60% of the time I kill a zombie.
Any idea what the issue could be?
