### ISSUE TITLE
Grinding detection continues in disabled worlds

### ISSUE THREAD

**Issue by SlimeDog** [Rocologo/MobHunting#646]
Spigot 1.15.2
MH 7.0.9-SNAPSHOT-B1012

We still get "grinding detected" messages in world_skyblock*, despite this configuration:
```
grinding:
  enable_grinding_detection: true

  # Put the names of the worlds here where you want to disable grinding detection
  # You would typically do this in creative worlds.
  disable_grinding_detection_in_worlds:
  - world
  - world_nether
  - world_the_end
  - world_skyblock
  - world_skyblock_nether
  - world_skyblock_the_end
```
