### ISSUE TITLE
Mobhunter not detecting grinding for StackMobs

### ISSUE THREAD

**Issue by NessXXIII** [Rocologo/MobHunting#723]
MobHunting 8.0.1
StackMob 5.6.2
This server is running Paper version git-Paper-774 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Paper-756 (MC: 1.16.5)

So when I set the config to restrict grinding on stacked mobs the rewards are still being given.
Here is the current configuration in case ive messed something up here.

https://pastebin.com/U3bV1LMu

**Comment by Rocologo** [comment]
Maybe the config not 100% clear on the

when you set 

grinding_stacked_mobs_allowed: false

You will still get money for the number of mobs a player is allowed to kill in an Area (Area grinding) og in a given timeframe (speed grinding)

```
  area:
    detect_grinding_areas: false
    grinding_detection_range: 15
    grinding_detection_number_of_death: 20
    blacklist_player_grinding_spots_as_server_worldwide_spots: false

  # Speed grinding detection.
  # Limit the number of mobs which can be killed with in a given timeframe
  speed_grinding:
    detect_speed_grinding: false
    time_frame: 120.0
    no_of_mobs: 60

```
So the player are still allowed to kill 20 mobs in an area og 60 mobs in 120 seconds.

If you set

grinding_stacked_mobs_allowed: true

The player is allowed to kill as many stacked mpbs as he want to. That would say the hole stack without getting a penalty.
