### ISSUE TITLE
negative rewards (fines for killing passive mobs) affects the achiviements

### ISSUE THREAD

**Issue by meswrex** [Rocologo/MobHunting#94]
It appears that having negative numbers for some rewards means that the hunter bonuses will still be applied. Eg. get fined for each mob, but get the hunter bonus when enough have been killed. If confirmed, can the plugin be updated to turn off hunter bonuses when the number is less than or equal to zero?

**Comment by Rocologo** [comment]
Please  help me testing V3.4.7-SNAPSHOT build 116 or newer.
http://jenkins.lindegaard.one:8180/job/MobHunting/116/

Let me know if it works?

**Comment by meswrex** [comment]
Doesn't seem to have changed; hopefully it's not something with my config. Here are the relevant sections:

```
passive:
  chicken: '-1'
  chicken-cmd: execute @p ~ ~ ~ particle reddust ~ ~1 ~ 0.25 0.25 0.25 1 50|execute @p ~ ~ ~ playsound minecraft:block.anvil.land voice @p
  chicken-cmd-desc: Passive Mob Kill! You have been fined!
  chicken-cmd-run-frequency: 100
  chicken-cmd-run-frequency-base: 100
```
```
achievement_levels:
  chicken_level1: 0
```
```
achievements:
  hunt-begins: 500.0
  hunter1: 1000.0
```

I deleted my mobhunting.db, used \summon Chicken, killed the chicken, then got this message:
```
Special Kill Awarded! MobHunting
Make your first hunt. There are more achievements to get all to do with interesting or unique ways to kill mobs.
You have been awarded 500.00 Emeralds
Special Kill Awarded! MobHunting
Hunt 0 Chickens
You have been awarded 1000.00 Emeralds
[Server: Given [Gold Ingots]*5 to Meswrex]
Enjoy your 5 Gold Ingots
Passive Mob Kill! You have been fined!
```
